initial static pages
codeforamerica/sb_reentry_app pull request #33
Opened 2021-03-02 16:27 UTC by vsauceda-cfa

2021-03-02 18:50 UTC, timmalstead-cfa requested changes
@vsauceda-cfa Looking good! Keep at it!

2021-03-02 18:50 UTC, timmalstead-cfa commented on package.json
> +    "styled-components": "^5.2.1",
is there a need for `styled-components` AND `material-ui`?

2021-03-02 18:50 UTC, timmalstead-cfa commented on package.json
> +    },
good call on below!

2021-03-02 18:50 UTC, timmalstead-cfa commented on components/Burger.module.js
> +import styled from 'styled-components'
I'm not seeing the Burger render at all. Is there something that I am missing?

2021-03-02 18:50 UTC, timmalstead-cfa commented on components/Burger.tsx
> +import NextLink from 'next/link'
see comment on `Burger.module.js`

2021-03-02 18:50 UTC, timmalstead-cfa commented on components/BurgerItems.module.js
> +import styled from 'styled-components'
see comment on `Burger.module.js`

2021-03-02 18:50 UTC, timmalstead-cfa commented on components/BurgerItems.tsx
> +import NextLink from 'next/link'
see comment on `Burger.module.js`

2021-03-02 18:50 UTC, timmalstead-cfa commented on pages/success-stories/index.tsx
> +            style={{ width: '100%', marginRight: '3rem', padding: '2rem' }}
Can we center this? Also, I think we would do well to keep a width of 90% across the project for "holder" components and pages. I used this on the tiles on the front page and think it gives it a clean and modern look. What are your thoughts?

2021-03-02 18:50 UTC, timmalstead-cfa commented on pages/know-your-rights/index.tsx
> +import CardActions from '@material-ui/core/CardActions'
please delete unused imports.

you can run `yarn run lint-es` to help catch these kinds of problems

2021-03-02 18:50 UTC, timmalstead-cfa commented on pages/know-your-rights/index.tsx
> +import Link from '@material-ui/core/Link'
unused

2021-03-02 18:50 UTC, timmalstead-cfa commented on pages/know-your-rights/index.tsx
> +const useStyles = makeStyles((theme: Theme) =>
props unused

2021-03-02 18:50 UTC, timmalstead-cfa commented on pages/know-your-rights/index.tsx
> +  const [activeItem, setActiveItem] = React.useState({})
state item unused

2021-03-02 18:50 UTC, timmalstead-cfa commented on pages/know-your-rights/index.tsx
> +  console.log('styles')
please delete console statements. user should not see debug info.

2021-03-02 18:50 UTC, timmalstead-cfa commented on pages/know-your-rights/index.tsx
> +  const flyers = [
less expensive to place static info outside of components

2021-03-02 18:50 UTC, timmalstead-cfa commented on pages/know-your-rights/index.tsx
> +                {/* <img
please delete commented text

2021-03-02 18:50 UTC, timmalstead-cfa commented on pages/know-your-rights/index.tsx
> +import Head from 'next/head'
General thoughts: can we center this page?
This is still pending addition of Spanish language copy, yes?

2021-03-02 18:50 UTC, timmalstead-cfa commented on pages/know-your-rights/index.tsx
> +            <Modal
Modals not rendering documents properly
![Screen Shot 2021-03-02 at 10 17 22 AM](https://user-images.githubusercontent.com/72828520/109695485-cbaa6f80-7b40-11eb-8cad-a1a99d7aace4.png)
![Screen Shot 2021-03-02 at 10 17 12 AM](https://user-images.githubusercontent.com/72828520/109695489-ce0cc980-7b40-11eb-9057-88213c4f2b6f.png)

2021-03-02 18:50 UTC, timmalstead-cfa commented on pages/know-your-rights/index.tsx
> +                        title="Contemplative Reptile"
Contemplative Reptile?

2021-03-02 18:50 UTC, timmalstead-cfa commented on pages/about-us/index.tsx
> +        style={{ marginTop: '10rem' }}
I don't think the top margin needs to be this large

2021-03-02 18:50 UTC, timmalstead-cfa commented on pages/about-us/index.tsx
> +import Head from 'next/head'
General thoughts: same comment regarding multiple ternarys for language check as Success Stories, it's easier to do one check and then load that.

2021-03-02 18:50 UTC, timmalstead-cfa commented on hooks/useOnClickOutside.tsx
> +import { useEffect } from 'react'
I'm not certain I understand how you're using this hook.

2021-03-02 18:50 UTC, timmalstead-cfa commented on components/Header.tsx
> +import BurgerItems from './BurgerItems'
Not rendering

2021-03-02 18:50 UTC, timmalstead-cfa commented on components/Header.tsx
> +  const { language } = useLanguage()
unused

2021-03-02 18:50 UTC, timmalstead-cfa commented on components/Header.tsx
> +  useOnClickOutside(node, () => setOpen(false))
how is this being used?

2021-03-02 18:50 UTC, timmalstead-cfa commented on components/Header.tsx
>  import NextLink from 'next/link'
General thoughts: the hamburger buttons are nor rendering.

Also, the links are not responsive and are not appearing at all in smaller views.
![Screen Shot 2021-03-02 at 10 38 34 AM](https://user-images.githubusercontent.com/72828520/109698275-1b3e6a80-7b44-11eb-8659-87c242249348.png)
![Screen Shot 2021-03-02 at 10 38 16 AM](https://user-images.githubusercontent.com/72828520/109698281-1bd70100-7b44-11eb-9462-7f8506606e25.png)

2021-03-02 18:50 UTC, timmalstead-cfa commented on pages/checklist/index.tsx
> +import ListItemSecondaryAction from '@material-ui/core/ListItemSecondaryAction'
unused

2021-03-02 18:50 UTC, timmalstead-cfa commented on pages/checklist/index.tsx
> +import Head from 'next/head'
General thoughts: can we make this smaller? it's really big for a page and is loading slowly as a result. can you write the text in the constants folder and map that?

Also, can we do this at 90% width and center by default?

2021-03-02 18:50 UTC, timmalstead-cfa commented on pages/checklist/index.tsx
> +const probations = [
this is pretty large, can it go in the constants folder or be called from data?

2021-03-02 18:50 UTC, timmalstead-cfa commented on pages/checklist/index.tsx
> +        <title>{`Santa Barbara Reentry | ${
same comment concerning languages as success stories, i think we can slim down the language selection

2021-03-02 18:54 UTC, timmalstead-cfa commented
@vsauceda-cfa as a general thing, you will want to have more commits than one for a major feature change like this. Try committing each time you finish working on a file.

2021-03-02 21:19 UTC, vsauceda-cfa commented on pages/success-stories/index.tsx
> +            </Typography>
I seen that. Moved grid container outside of the .map

2021-03-12 00:53 UTC, timmalstead-cfa approved these changes
great work @vsauceda-cfa !

2021-03-12 00:53 UTC, merged